version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: cooking_django_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: >
      redis-server
      --save 900 1
      --save 300 10
      --save 60 10000
      --appendonly yes
      --appendfsync everysec
      --dir /data
      --dbfilename dump.rdb
      --appendfilename appendonly.aof
    networks:
      - cooking_django-network

  db:
    image: postgres:15
    container_name: cooking_django_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    networks:
      - cooking_django-network

  django:
    build:
      context: ./
    container_name: cooking_django_app
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - cooking_django-network
    entrypoint: ["/entrypoint.sh"]

volumes:
  redis-data:
  postgres_data:

networks:
  cooking_django-network:
    driver: bridge
