version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: >
      redis-server
      --save 900 1
      --save 300 10
      --save 60 10000
      --appendonly yes
      --appendfsync everysec
      --dir /data
      --dbfilename dump.rdb
      --appendfilename appendonly.aof

  # Сервис с Django
  django:
    build: ./path_to_django_project  # Путь к твоему проекту с Django (если у тебя есть Dockerfile)
    container_name: django_app
    depends_on:
      - redis  # Убедимся, что Redis поднимется до Django
    ports:
      - "8000:8000"  # Открываем порт для доступа к Django-приложению
    environment:
      - SECRET_KEY=${SECRET_KEY}  # Используем SECRET_KEY из .env
      - REDIS_HOST=redis  # Указываем имя контейнера Redis как хост
      - REDIS_PORT=6379
      - REDIS_PASSWORD=your-redis-password  # Устанавливаем пароль Redis
    volumes:
      - ./path_to_django_project:/app  # Монтируем локальный проект в контейнер для удобства разработки
    command: python manage.py runserver 0.0.0.0:8000  # Команда для запуска Django

volumes:
  redis-data:  # Том для хранения данных Redis

